use anyhow::Result;

use crate::models::safety::SafetyLevel;
use crate::models::scan::{ScanCategory, ScanItem};

use super::{calculate_dir_size_async, get_last_modified, hash_id};

/// Scan for Ruby gem and bundler caches.
pub async fn scan_ruby_cache() -> Result<Vec<ScanItem>> {
    let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("No home directory"))?;
    let mut items = Vec::new();

    let cache_locations = [
        (home.join(".gem"), "Ruby gem cache", "Downloaded gem files - re-downloaded with gem install"),
        (home.join(".bundle/cache"), "Bundler cache", "Cached bundle downloads - re-downloaded with bundle install"),
        (home.join("Library/Caches/com.apple.rubygems"), "RubyGems cache", "System RubyGems cache - regenerated automatically"),
    ];

    for (path, name, description) in cache_locations {
        if !path.exists() {
            continue;
        }
        let size = calculate_dir_size_async(&path).await?;
        if size < 10_000_000 {
            continue;
        }
        let path_str = path.to_string_lossy().to_string();
        items.push(ScanItem {
            id: hash_id(&path_str, "ruby_cache"),
            path: path_str,
            display_name: name.to_string(),
            description: description.to_string(),
            size_bytes: size,
            safety: SafetyLevel::Green,
            category: ScanCategory::RubyCache,
            last_modified: get_last_modified(&path),
        });
    }

    Ok(items)
}

/// Scan for .NET/NuGet caches.
pub async fn scan_dotnet_cache() -> Result<Vec<ScanItem>> {
    let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("No home directory"))?;
    let mut items = Vec::new();

    let cache_locations = [
        (home.join(".nuget/packages"), "NuGet package cache", "Downloaded NuGet packages - re-downloaded on next build"),
        (home.join(".dotnet"), ".NET SDK cache", ".NET SDK tools and runtime cache"),
        (home.join(".local/share/NuGet"), "NuGet cache (alt)", "Downloaded NuGet packages - re-downloaded on next build"),
    ];

    for (path, name, description) in cache_locations {
        if !path.exists() {
            continue;
        }
        let size = calculate_dir_size_async(&path).await?;
        if size < 10_000_000 {
            continue;
        }
        let path_str = path.to_string_lossy().to_string();
        items.push(ScanItem {
            id: hash_id(&path_str, "dotnet_cache"),
            path: path_str,
            display_name: name.to_string(),
            description: description.to_string(),
            size_bytes: size,
            safety: SafetyLevel::Green,
            category: ScanCategory::DotnetCache,
            last_modified: get_last_modified(&path),
        });
    }

    Ok(items)
}

/// Scan for Flutter/Dart pub cache.
pub async fn scan_flutter_cache() -> Result<Vec<ScanItem>> {
    let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("No home directory"))?;
    let mut items = Vec::new();

    let cache_locations = [
        (home.join(".pub-cache"), "Dart pub cache", "Downloaded Dart packages - re-downloaded with dart pub get"),
        (home.join("Library/Caches/flutter"), "Flutter cache", "Flutter SDK cache - regenerated by Flutter"),
        (home.join(".dartServer"), "Dart analysis server cache", "Dart language server cache - regenerated automatically"),
    ];

    for (path, name, description) in cache_locations {
        if !path.exists() {
            continue;
        }
        let size = calculate_dir_size_async(&path).await?;
        if size < 10_000_000 {
            continue;
        }
        let path_str = path.to_string_lossy().to_string();
        items.push(ScanItem {
            id: hash_id(&path_str, "flutter_cache"),
            path: path_str,
            display_name: name.to_string(),
            description: description.to_string(),
            size_bytes: size,
            safety: SafetyLevel::Green,
            category: ScanCategory::FlutterCache,
            last_modified: get_last_modified(&path),
        });
    }

    Ok(items)
}

/// Scan for CocoaPods cache.
pub async fn scan_cocoapods_cache() -> Result<Vec<ScanItem>> {
    let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("No home directory"))?;
    let mut items = Vec::new();

    let cache_locations = [
        (home.join("Library/Caches/CocoaPods"), "CocoaPods cache", "Downloaded pod specs and sources - re-downloaded with pod install"),
        (home.join(".cocoapods"), "CocoaPods repos", "CocoaPods spec repositories - re-cloned when needed"),
    ];

    for (path, name, description) in cache_locations {
        if !path.exists() {
            continue;
        }
        let size = calculate_dir_size_async(&path).await?;
        if size < 10_000_000 {
            continue;
        }
        let path_str = path.to_string_lossy().to_string();
        items.push(ScanItem {
            id: hash_id(&path_str, "cocoapods_cache"),
            path: path_str,
            display_name: name.to_string(),
            description: description.to_string(),
            size_bytes: size,
            safety: SafetyLevel::Green,
            category: ScanCategory::CocoaPodsCache,
            last_modified: get_last_modified(&path),
        });
    }

    Ok(items)
}

/// Scan for PHP Composer cache.
pub async fn scan_composer_cache() -> Result<Vec<ScanItem>> {
    let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("No home directory"))?;
    let mut items = Vec::new();

    let cache_locations = [
        (home.join(".composer/cache"), "Composer cache", "Downloaded PHP packages - re-downloaded with composer install"),
        (home.join("Library/Caches/composer"), "Composer cache (Library)", "Downloaded PHP packages - re-downloaded with composer install"),
    ];

    for (path, name, description) in cache_locations {
        if !path.exists() {
            continue;
        }
        let size = calculate_dir_size_async(&path).await?;
        if size == 0 {
            continue;
        }
        let path_str = path.to_string_lossy().to_string();
        items.push(ScanItem {
            id: hash_id(&path_str, "composer_cache"),
            path: path_str,
            display_name: name.to_string(),
            description: description.to_string(),
            size_bytes: size,
            safety: SafetyLevel::Green,
            category: ScanCategory::ComposerCache,
            last_modified: get_last_modified(&path),
        });
    }

    Ok(items)
}

/// Scan for IDE and editor caches (JetBrains, VS Code, Cursor).
pub async fn scan_ide_caches() -> Result<Vec<ScanItem>> {
    let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("No home directory"))?;
    let mut items = Vec::new();

    // VS Code / Cursor workspace storage
    let ide_caches = [
        (home.join("Library/Application Support/Code/Cache"), "VS Code cache", "VS Code application cache - regenerated on launch"),
        (home.join("Library/Application Support/Code/CachedData"), "VS Code cached data", "VS Code cached extension data - regenerated on launch"),
        (home.join("Library/Application Support/Code/CachedExtensionVSIXs"), "VS Code extension cache", "Downloaded extension packages - re-downloaded when needed"),
        (home.join("Library/Application Support/Cursor/Cache"), "Cursor cache", "Cursor editor cache - regenerated on launch"),
        (home.join("Library/Application Support/Cursor/CachedData"), "Cursor cached data", "Cursor cached extension data - regenerated on launch"),
    ];

    for (path, name, description) in ide_caches {
        if !path.exists() {
            continue;
        }
        let size = calculate_dir_size_async(&path).await?;
        if size < 50_000_000 {
            continue;
        }
        let path_str = path.to_string_lossy().to_string();
        items.push(ScanItem {
            id: hash_id(&path_str, "ide_caches"),
            path: path_str,
            display_name: name.to_string(),
            description: description.to_string(),
            size_bytes: size,
            safety: SafetyLevel::Green,
            category: ScanCategory::IdeCaches,
            last_modified: get_last_modified(&path),
        });
    }

    // JetBrains old version caches - scan for dirs in ~/Library/Caches/JetBrains
    let jb_cache_dir = home.join("Library/Caches/JetBrains");
    if jb_cache_dir.exists() {
        if let Ok(entries) = std::fs::read_dir(&jb_cache_dir) {
            for entry in entries.flatten() {
                if entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false) {
                    let path = entry.path();
                    let size = calculate_dir_size_async(&path).await?;
                    if size < 50_000_000 {
                        continue;
                    }
                    let name = entry.file_name().to_string_lossy().to_string();
                    let path_str = path.to_string_lossy().to_string();
                    items.push(ScanItem {
                        id: hash_id(&path_str, "ide_caches"),
                        path: path_str,
                        display_name: format!("JetBrains {} cache", name),
                        description: "JetBrains IDE cache - regenerated by the IDE".to_string(),
                        size_bytes: size,
                        safety: SafetyLevel::Green,
                        category: ScanCategory::IdeCaches,
                        last_modified: get_last_modified(&path),
                    });
                }
            }
        }
    }

    Ok(items)
}
